name: D

on:
  push:
    # branches: [ main ]
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-24.04-arm, ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: dlang-community/setup-dlang@v2
        with:
          compiler: ldc-master

      - name: prepare-linux
        if: runner.os == 'Linux'
        run: |
            sudo apt-get update
            sudo apt-get install libglu1-mesa-dev mesa-common-dev xorg-dev libasound-dev

      # - name: (Dub) Build Native
      #   run: dub -- --download-emsdk --download-zig --download-imgui --download-sokol-tools
      - name: (Dub) Build Native
        run: dub build -v
      - name: (Dub) Build Wasm32
        run: dub build -c emscripten -v
